apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/c/Users/Sumit/OneDrive/Desktop/link/two/two-tier-flask-app/mysqldata